# Setup
title: Carina Guo
tagline: Student at Richard Montgomery HS
baseurl: ""
paginate: 1

# About/contact
author:
  name: Carina Guo
  url: http://127.0.0.1:4000/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
